const API_KEY = "d38e8f9e";

const genreMovies = {
  Action: [
    "Mad Max: Fury Road", "John Wick", "Gladiator", "Die Hard", "The Dark Knight",
    "Avengers: Endgame", "Black Panther", "Spider-Man: No Way Home", "Logan", "The Matrix",
    "Inception", "Terminator 2: Judgment Day", "The Bourne Identity", "Casino Royale",
    "Captain America: Civil War", "Thor: Ragnarok", "Wonder Woman", "Guardians of the Galaxy",
    "Jurassic Park", "Indiana Jones: Raiders of the Lost Ark", "The Avengers", "Iron Man",
    "Man of Steel", "Star Wars: The Force Awakens", "X-Men: Days of Future Past", "Deadpool",
    "The Equalizer", "Kingsman: The Secret Service", "Mission Impossible: Fallout", "Rogue One",
    "Edge of Tomorrow", "Black Widow", "Doctor Strange", "Ant-Man", "Shang-Chi", "Venom",
    "The Dark Knight Rises", "Batman Begins", "Spider-Man: Homecoming", "Captain Marvel",
    "Thor", "Iron Man 2", "Iron Man 3", "Avengers: Infinity War", "The Wolverine",
    "Deadpool 2", "The Hunger Games", "Catching Fire", "Mockingjay Part 1", "Mockingjay Part 2",
    "The Expendables", "The Expendables 2", "The Expendables 3", "Kick-Ass", "Kick-Ass 2",
    "Furious 7", "Fast & Furious 6", "Fast Five", "Fast & Furious 8", "Hobbs & Shaw",
    "Spider-Man 2", "Spider-Man 3", "The Amazing Spider-Man", "The Amazing Spider-Man 2",
    "Captain America: The Winter Soldier", "Captain America: The First Avenger", "Ant-Man and the Wasp",
    "Guardians of the Galaxy Vol. 2", "Doctor Strange in the Multiverse of Madness",
    "Thor: Love and Thunder", "Black Panther: Wakanda Forever", "Avengers: Age of Ultron",
    "Iron Man 3", "The Incredible Hulk", "Shang-Chi and the Legend of the Ten Rings",
    "Venom: Let There Be Carnage", "Spider-Man: Far From Home", "Spider-Man: No Way Home",
    "Guardians of the Galaxy", "Avengers", "Batman v Superman: Dawn of Justice", "Aquaman",
    "Justice League", "Suicide Squad", "Wonder Woman 1984", "The Flash", "Black Adam",
    "Doctor Strange", "Thor: Ragnarok", "Captain Marvel", "Ant-Man", "Iron Man",
    "The Dark Knight", "Logan", "Deadpool", "X-Men: First Class", "X-Men: Apocalypse",
    "Man of Steel", "Batman Begins", "Spider-Man", "Spider-Man 2", "Spider-Man 3", "The Amazing Spider-Man",
    "The Amazing Spider-Man 2", "The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War",
    "Avengers: Endgame", "Guardians of the Galaxy", "Guardians of the Galaxy Vol. 2", "Thor",
    "Thor: The Dark World", "Thor: Ragnarok", "Doctor Strange", "Black Panther", "Black Panther: Wakanda Forever", "The Raid: Redemption", "The Raid 2", "Oldboy", "Crouching Tiger, Hidden Dragon", "Ip Man", "Ip Man 2", "Ip Man 3", "Ip Man 4: The Finale", "Hero", "House of Flying Daggers", "Police Story", "Police Story 2", "Police Story 3: Supercop", "Hard Boiled", "Drunken Master", "Drunken Master II", "Ong-Bak: Muay Thai Warrior", "Ong-Bak 2", "Ong-Bak 3", "Chocolate", "The Protector", "The Man from Nowhere", "Léon: The Professional", "Taken", "Taken 2", "Taken 3", "La Femme Nikita", "Point of No Return", "The Transporter", "Transporter 2", "Transporter 3", "Kickboxer", "Bloodsport", "Timecop", "Sudden Death", "Cliffhanger", "Con Air", "Face/Off", "Broken Arrow", "Heat", "The Rock", "The Last Boy Scout", "Demolition Man", "Patriot Games", "Clear and Present Danger", "Under Siege", "Under Siege 2: Dark Territory", "Total Recall (1990)", "Total Recall (2012)", "Minority Report", "Collateral", "The Losers", "Smokin' Aces", "Wanted", "3:10 to Yuma (2007)", "The Magnificent Seven", "The Magnificent Seven (2016)", "Unforgiven", "The Good, the Bad and the Ugly", "Django Unchained", "Blade", "Blade II", "Blade: Trinity", "Spawn", "Ultraviolet", "Salt", "Haywire", "Sicario: Day of the Soldado", "Sicario", "Man on Fire", "The Book of Eli", "Hell or High Water", "Wind River", "Den of Thieves", "Cellular", "Running Scared", "Ronin", "Mr. & Mrs. Smith", "The Italian Job (2003)", "Layer Cake", "RocknRolla", "Revolver", "Children of Men", "Equilibrium", "V for Vendetta", "The Bourne Supremacy", "The Bourne Ultimatum", "Jason Bourne", "The Accountant", "Safe", "Stolen", "Black Hawk Down", "Lethal Weapon", "Lethal Weapon 2", "Lethal Weapon 3", "Lethal Weapon 4", "A Better Tomorrow", "A Better Tomorrow II", "Hardcore Henry", "Kingsman: The Golden Circle", "Mad Max (1979)", "Mad Max 2: The Road Warrior", "Mad Max Beyond Thunderdome", "Warrior", "The Foreigner", "The Man from U.N.C.L.E.", "Red", "Red 2", "Jack Reacher", "Jack Reacher: Never Go Back", "Wrath of Man", "The Gray Man", "Extraction", "Extraction 2", "The Outpost", "13 Hours: The Secret Soldiers of Benghazi", "Lone Survivor", "Act of Valor", "Zero Dark Thirty", "American Sniper", "The Last of the Mohicans", "Black Hawk Down (1998)", "Tears of the Sun", "Behind Enemy Lines", "A Walk Among the Tombstones", "The Equalizer 2", "Cold Pursuit", "The Nice Guys", "Kiss Kiss Bang Bang", "The Man with the Iron Fists", "Goldfinger", "From Russia with Love", "Dr. No", "Thunderball", "You Only Live Twice", "On Her Majesty's Secret Service", "Skyfall", "Spectre", "No Time to Die", "GoldenEye", "Tomorrow Never Dies", "The World Is Not Enough", "Quantum of Solace", "Top Gun", "Top Gun: Maverick", "S.W.A.T.", "The Negotiator", "The Peacemaker", "The Specialist", "The Mechanic (2011)", "Killer Elite", "Hard Target", "Cobra", "Rambo: First Blood", "Rambo: First Blood Part II", "Rambo III", "Rambo (2008)", "Rambo: Last Blood", "Death Wish (1974)", "Death Wish (2018)", "The Punisher (2004)", "Punisher: War Zone", "Law Abiding Citizen", "Safe House", "The Gunman", "Hanna", "The Long Kiss Goodnight", "The Rundown", "Bravo Two Zero", "The Killer", "Brotherhood of the Wolf", "District B13", "District B13: Ultimatum", "The Longest Yard (2005)", "Escape Plan", "Escape Plan 2: Hades", "Assault on Precinct 13 (1976)", "Assault on Precinct 13 (2005)", "Black Rain", "Blue Thunder", "The Taking of Pelham 123 (2009)", "Baby Driver", "Drive", "Bullitt", "Point Break (1991)", "Set It Off", "Training Day", "The Hunted", "The Jackal", "Mad Max: Fury Road (alternate cut)", "The Best of the Best", "Shoot 'Em Up", "The Replacement Killers", "Black Rain (1989)", "The Taking of Pelham One Two Three (1974)", "Wheelman", "Baby Boy", "Baby Driver (repeat safe-check)", "Bullitt (1968)", "The Driver", "The Hunted (1995)", "Point Break (2015)", "Shoot 'Em Up (2007)", "The Killer (1989)", "Le Pacte des Loups (Brotherhood of the Wolf)", "Battle Royale", "Battle Royale II", "The 36th Chamber of Shaolin", "Shaolin Soccer", "Kickboxer: Vengeance", "Kickboxer: Retaliation", "The Best of the Best 2", "The Protector (1985)", "The Longest Day", "The Warlords", "A Touch of Sin", "Ip Man: The Final Fight", "Brother", "Shinobi: Heart Under Blade", "13 Assassins", "Silence (action sequences)", "Red Cliff", "The Legend of Drunken Master", "The Yellow Sea", "The Chaser", "The Man from Nowhere (2010)", "The Berlin File", "Cold War (Hong Kong action)", "Dragon Blade", "SPL: Sha Po Lang", "Project A", "Project A Part II", "Enter the Dragon", "Fist of Fury", "The 47 Ronin (2013)", "The Bourne Legacy"

  ],
  Comedy: [
    "Superbad", "Step Brothers", "The Hangover", "Bridesmaids", "The 40-Year-Old Virgin",
    "Anchorman", "Pineapple Express", "Crazy Rich Asians", "Jumanji: Welcome to the Jungle",
    "21 Jump Street", "22 Jump Street", "Ted", "Ted 2", "Dumb and Dumber", "Dumb and Dumber To",
    "Hot Fuzz", "Shaun of the Dead", "Zombieland", "Zombieland: Double Tap", "Game Night",
    "The Other Guys", "Horrible Bosses", "Horrible Bosses 2", "Neighbors", "Neighbors 2",
    "Pitch Perfect", "Pitch Perfect 2", "Pitch Perfect 3", "Ferris Bueller's Day Off",
    "Groundhog Day", "Night at the Museum", "Night at the Museum: Battle of the Smithsonian",
    "Night at the Museum: Secret of the Tomb", "21", "22", "Anchorman 2", "Little Miss Sunshine",
    "Mean Girls", "The Intern", "Spy", "Crazy, Stupid, Love", "Clueless", "The Mask",
    "Ace Ventura: Pet Detective", "Ace Ventura: When Nature Calls", "Legally Blonde",
    "Legally Blonde 2", "Napoleon Dynamite", "The Grand Budapest Hotel", "Rushmore",
    "School of Rock", "Wayne's World", "Wayne's World 2", "Anchorman", "Anchorman 2",
    "The Heat", "The Nice Guys", "21 Jump Street", "22 Jump Street", "Role Models", "Ted",
    "Ted 2", "Horrible Bosses", "Horrible Bosses 2", "Get Smart", "Hot Fuzz",
    "Shaun of the Dead", "The World's End", "Ghostbusters", "Ghostbusters 2016", "Ghostbusters 2",
    "Pineapple Express", "The Other Guys", "Central Intelligence", "Jumanji",
    "Jumanji: The Next Level", "Crazy Rich Asians", "Hustlers", "Blockers", "Wine Country",
    "Vacation", "Vacation 2", "Ride Along", "Ride Along 2", "Identity Thief", "Daddy's Home",
    "Daddy's Home 2", "Fist Fight", "Why Him?", "Office Christmas Party", "Bad Moms", "Bad Moms 2", "Super Troopers", "Super Troopers 2", "Forgetting Sarah Marshall", "Get Him to the Greek",
"I Love You, Man", "Role Models", "Knocked Up", "This Is 40", "The Interview",
"Neighbors", "The Dictator", "Borat", "Borat Subsequent Moviefilm", "Brüno",
"The Campaign", "Talladega Nights: The Ballad of Ricky Bobby", "Blades of Glory",
"Semi-Pro", "Anchorman: The Legend of Ron Burgundy", "Land of the Lost",
"The Other Woman", "Trainwreck", "No Hard Feelings", "Easy A", "Superstar",
"Baby Mama", "Sisters", "The House Bunny", "She's the Man", "The Duff",
"Booksmart", "Eighth Grade", "Good Boys", "Long Shot", "My Big Fat Greek Wedding",
"My Big Fat Greek Wedding 2", "Legally Blonde 3", "The Proposal", "The Ugly Truth",
"Friends with Benefits", "No Strings Attached", "Crazy People", "Tropic Thunder",
"Dodgeball: A True Underdog Story", "Zoolander", "Zoolander 2", "Meet the Parents",
"Meet the Fockers", "Little Fockers", "Along Came Polly", "There's Something About Mary",
"Me, Myself & Irene", "Liar Liar", "Bruce Almighty", "Yes Man", "The Cable Guy",
"The Truman Show", "Fun with Dick and Jane", "Mr. Popper’s Penguins", "The Mask 2: Son of the Mask",
"Click", "50 First Dates", "Big Daddy", "Happy Gilmore", "Billy Madison",
"The Waterboy", "The Longest Yard", "Just Go With It", "Blended", "Grown Ups",
"Grown Ups 2", "You Don’t Mess with the Zohan", "That’s My Boy", "Jack and Jill",
"Pixels", "Hubie Halloween", "Murder Mystery", "Murder Mystery 2",
"The Wedding Singer", "Punch-Drunk Love", "Funny People", "The Do-Over", "The Ridiculous 6",
"The Benchwarmers", "The Ringer", "Dumb and Dumberer: When Harry Met Lloyd",
"Rat Race", "Mr. Bean’s Holiday", "Bean", "Johnny English", "Johnny English Reborn",
"Johnny English Strikes Again", "Bridget Jones’s Baby", "Love Actually", "About Time",
"Four Weddings and a Funeral", "Notting Hill", "The Boat That Rocked",
"Death at a Funeral (UK)", "In the Loop", "The Death of Stalin", "The Trip",
"The Trip to Italy", "The Trip to Spain", "The Trip to Greece", "Paddington",
"Paddington 2", "Wallace & Gromit: The Curse of the Were-Rabbit", "A Shaun the Sheep Movie",
"Chicken Run", "Flushed Away", "Hector and the Search for Happiness",
"The Inbetweeners Movie", "The Inbetweeners 2", "Absolutely Fabulous: The Movie",
"Nuns on the Run", "A Fish Called Wanda", "Fierce Creatures", "The Full Monty",
"Kinky Boots", "Calendar Girls", "Brassed Off", "The Commitments",
"Trainspotting", "T2 Trainspotting", "The Guard", "Calvary", "Waking Ned Devine",
"Local Hero", "Whisky Galore!", "The Man Who Knew Too Little", "Analyze This",
"Analyze That", "Deuce Bigalow: Male Gigolo", "Deuce Bigalow: European Gigolo",
"EuroTrip", "Road Trip", "Sex Drive", "American Pie", "American Pie 2",
"American Wedding", "American Reunion", "Van Wilder", "Accepted", "Old School",
"Wedding Crashers", "The Internship", "The Break-Up", "Couples Retreat",
"Dodgeball", "Office Space", "The Internship", "Horrible Bosses (unrated)",
"Harold & Kumar Go to White Castle", "Harold & Kumar Escape from Guantanamo Bay",
"A Very Harold & Kumar Christmas", "Dude, Where’s My Car?", "The Girl Next Door",
"Waiting...", "Chef", "Burnt", "Julie & Julia", "Ratatouille", "The Hundred-Foot Journey",
"Eat Pray Love", "Julie & Julia", "The Terminal", "The Intern (Nancy Meyers)",
"The Holiday", "It’s Complicated", "Something’s Gotta Give", "What Women Want",
"Melinda and Melinda", "Midnight in Paris", "Vicky Cristina Barcelona",
"Manhattan Murder Mystery", "Bullets Over Broadway", "Small Time Crooks",
"The Royal Tenenbaums", "The Life Aquatic with Steve Zissou", "The Darjeeling Limited",
"Fantastic Mr. Fox", "Moonrise Kingdom", "Isle of Dogs", "Asteroid City",
"Jojo Rabbit", "Hunt for the Wilderpeople", "What We Do in the Shadows",
"Our Flag Means Death", "Eagle vs Shark", "Boy", "Thor: Ragnarok (comedy-heavy)",
"The Dish", "The Castle", "Muriel’s Wedding", "The Adventures of Priscilla, Queen of the Desert",
"Strictly Ballroom", "The Sapphires", "The Interview (Australian)", "Crackerjack",
"Kung Fu Hustle", "Shaolin Soccer", "Lost in Thailand", "Detective Chinatown",
"Detective Chinatown 2", "Detective Chinatown 3", "Goodbye Mr. Loser",
"Crazy Stone", "Flirting Scholar", "From Beijing with Love", "God of Cookery",
"King of Comedy (Stephen Chow)", "The Mermaid (2016)", "Journey to the West: Conquering the Demons",
"Journey to the West: The Demons Strike Back", "CJ7", "All's Well, Ends Well",
"Trick (Japanese)", "Thermae Romae", "Thermae Romae II", "Tampopo", "Shin Godzilla (satire elements)",
"Welcome to Dongmakgol", "Extreme Job", "Miss Granny", "Sunny (2011 Korean)",
"200 Pounds Beauty", "My Sassy Girl", "My Little Bride", "Miracle in Cell No. 7",
"Hello Ghost", "Luck-Key", "Exit", "Confession of Murder (dark comedy elements)",
"The Good, the Bad, the Weird", "Parasite (dark comedy)", "Barking Dogs Never Bite"
  ],
  Drama: [
    "Forrest Gump", "The Shawshank Redemption", "Fight Club", "The Godfather", "The Godfather: Part II",
    "The Green Mile", "Good Will Hunting", "The Social Network", "The Pianist", "Schindler's List",
    "A Beautiful Mind", "12 Years a Slave", "La La Land", "Whiplash", "The Imitation Game",
    "The Revenant", "Birdman", "Bohemian Rhapsody", "Joker", "Marriage Story", "Dallas Buyers Club",
    "The Theory of Everything", "Moneyball", "Spotlight", "The King’s Speech", "Room", "Lion",
    "Catch Me If You Can", "Revolutionary Road", "American Beauty", "There Will Be Blood", "Slumdog Millionaire",
    "The Fault in Our Stars", "The Help", "Hidden Figures", "Hacksaw Ridge", "Silver Linings Playbook",
    "Little Women", "The Curious Case of Benjamin Button", "Moulin Rouge!", "Gladiator", "The Departed",
    "Shutter Island", "The Prestige", "The Dark Knight", "The Dark Knight Rises", "Interstellar",
    "Inception", "Dunkirk", "Call Me by Your Name", "12 Angry Men", "One Flew Over the Cuckoo's Nest",
    "The Breakfast Club", "Dead Poets Society", "Boyhood", "Brooklyn", "Manchester by the Sea",
    "Blue Valentine", "Requiem for a Dream", "The Last Samurai", "The Notebook", "Atonement",
    "Pride & Prejudice", "Sense and Sensibility", "The English Patient", "Crash", "Traffic",
    "Erin Brockovich", "Hotel Rwanda", "Life of Pi", "Argo", "The Big Short", "Selma", "Lincoln",
    "Amadeus", "Lawrence of Arabia", "Taxi Driver", "Raging Bull", "Goodfellas", "Once Upon a Time in America",
    "The Untouchables", "Rocky", "Rocky II", "Rocky III", "Rocky IV", "Rocky Balboa", "Creed", "Creed II",
    "The Color Purple", "The Pianist", "The Boy in the Striped Pajamas", "The Kite Runner", "Life is Beautiful",
    "Cinema Paradiso", "The Social Network", "Atonement", "Joker", "Bohemian Rhapsody", "The Pursuit of Happyness", "Cast Away", "The Truman Show", "The Hours", "The Reader",
"Million Dollar Baby", "Mystic River", "The Departed", "Gran Torino", "Changeling",
"Unforgiven", "Invictus", "A Star Is Born", "The Great Gatsby", "Revolutionary Road (2008)",
"Marriage Story (2019)", "Lost in Translation", "Her", "Arrival", "127 Hours",
"Into the Wild", "Eternal Sunshine of the Spotless Mind", "The Perks of Being a Wallflower",
"Beautiful Boy", "Call Me by Your Name (2017)", "The Peanut Butter Falcon",
"The Spectacular Now", "The Edge of Seventeen", "Atonement (2007)", "Brooklyn (2015)",
"Lady Bird", "Moonlight", "If Beale Street Could Talk", "The Florida Project",
"The Whale", "Aftersun", "Past Lives", "Nomadland", "Sound of Metal",
"The Father", "Tár", "Oppenheimer", "The Iron Lady", "Philomena",
"The Queen", "Elizabeth", "Elizabeth: The Golden Age", "The Constant Gardener",
"The English Patient (1996)", "Atonement (expanded)", "Bridge of Spies",
"Sully", "Captain Phillips", "Cast Away (2000)", "Philadelphia", "Spotlight (2015)",
"Michael Clayton", "Syriana", "The Insider", "The Firm", "A Few Good Men",
"Jerry Maguire", "Rain Man", "Good Morning, Vietnam", "The Fisher King",
"The Aviator", "Catch Me If You Can (2002)", "The Terminal", "The Post",
"The Color of Money", "Casino", "The Irishman", "Raging Bull (1980)",
"Mean Streets", "Taxi Driver (1976)", "The King of Comedy", "Goodfellas (1990)",
"Hugo", "Gangs of New York", "The Wolf of Wall Street", "The Big Short (2015)",
"Moneyball (2011)", "Steve Jobs", "Jobs (2013)", "The Founder",
"The Social Dilemma", "The Ides of March", "Frost/Nixon", "The Good Shepherd",
"The Good German", "The Lives of Others", "The Baader Meinhof Complex",
"Downfall", "Good Bye Lenin!", "Run Lola Run", "The White Ribbon",
"The Counterfeiters", "Das Boot", "All Quiet on the Western Front (2022)",
"The Reader (2008)", "The Painted Veil", "Cold Mountain", "The English Patient (reprise)",
"Memoirs of a Geisha", "The Last Emperor", "Empire of the Sun", "The Killing Fields",
"Platoon", "Full Metal Jacket", "Born on the Fourth of July", "The Thin Red Line",
"Jarhead", "American Sniper (2014)", "Stop-Loss", "Brothers (2009)",
"Dear John (2008)", "The Lucky One", "My Sister’s Keeper", "The Time Traveler’s Wife",
"The Lake House", "The Best of Me", "The Longest Ride", "Safe Haven", "Me Before You",
"Five Feet Apart", "The Light Between Oceans", "Remember Me", "Never Let Me Go",
"One Day", "Blue Jasmine", "Match Point", "Vicky Cristina Barcelona",
"Café Society", "Midnight in Paris (2011)", "Manhattan", "Hannah and Her Sisters",
"Crimes and Misdemeanors", "The Purple Rose of Cairo", "Interiors", "September",
"Interstellar (drama emphasis)", "The Prestige (drama emphasis)",
"Insomnia", "Following", "Memento", "The Machinist", "Enemy (2013)",
"Prisoners (2013)", "Nightcrawler", "Drive", "Only God Forgives",
"The Place Beyond the Pines", "Blue Valentine (2010)", "Half Nelson",
"The Believer (2001)", "The Wrestler", "Black Swan", "Mother!", "Requiem for a Dream (2000)",
"The Fountain", "Pi", "The Whale (2022)", "The Wrestler (2008)", "Spotlight (expanded)",
"Good Will Hunting (1997)", "Finding Forrester", "Dead Poets Society (1989)",
"The Great Debaters", "Freedom Writers", "Lean on Me", "Dangerous Minds",
"Coach Carter", "Remember the Titans", "42", "The Blind Side", "Hidden Figures (2016)",
"A Beautiful Mind (2001)", "The Imitation Game (2014)", "The Theory of Everything (2014)",
"The Man Who Knew Infinity", "Gifted", "October Sky", "Rocketman",
"Ray", "Walk the Line", "8 Mile", "Straight Outta Compton", "La Vie en Rose",
"Nowhere Boy", "Control", "The Doors", "Bohemian Rhapsody (2018)", "Elvis",
"Whiplash (2014)", "August Rush", "Once", "Begin Again", "Sing Street",
"Inside Llewyn Davis", "The Pianist (2002)", "Shine", "Amadeus (1984)",
"The Soloist", "Green Book", "The Intouchables", "The Upside", "A Man Called Otto",
"The Hundred-Foot Journey", "The Lunchbox", "The Namesake", "Monsoon Wedding",
"Water (2005)", "Lagaan", "Swades", "Taare Zameen Par", "3 Idiots",
"PK", "Barfi!", "Piku", "Tamasha", "Highway", "Black (2005)",
"Guzaarish", "Dear Zindagi", "October (2018)", "Masaan", "The Disciple",
"Ship of Theseus", "Court (2014)", "Rang De Basanti", "Udaan", "Kai Po Che!",
"Article 15", "A Wednesday", "Pink", "Thappad", "Neerja", "Talvar",
"Raazi", "Haider", "Maqbool", "Omkara", "Black Friday", "Gully Boy",
"Zindagi Na Milegi Dobara", "Dil Chahta Hai", "Rock On!!", "Wake Up Sid",
"Kapoor & Sons", "Tamasha (2015)", "Lunchbox (India)", "The Great Indian Kitchen",
"Super Deluxe", "Visaranai", "Jigarthanda", "Asuran", "Drishyam", "Drishyam 2",
"Kaala", "Vikram Vedha", "KGF: Chapter 1", "KGF: Chapter 2", "Article 370 (2024)"

  ],
  Horror: [
    "Get Out", "A Quiet Place", "Hereditary", "It", "It Chapter Two", "The Conjuring",
    "The Conjuring 2", "Annabelle", "Annabelle: Creation", "Annabelle Comes Home",
    "Insidious", "Insidious: Chapter 2", "Insidious: Chapter 3", "Insidious: The Last Key",
    "The Nun", "The Nun 2", "The Exorcist", "The Exorcist II", "The Exorcist III", "Sinister",
    "Sinister 2", "Paranormal Activity", "Paranormal Activity 2", "Paranormal Activity 3",
    "Paranormal Activity 4", "Paranormal Activity: The Ghost Dimension", "The Ring", "The Ring 2",
    "The Grudge", "The Grudge 2", "The Grudge 3", "Lights Out", "Bird Box", "The Cabin in the Woods",
    "Don't Breathe", "Don't Breathe 2", "The Babadook", "Midsommar", "It Follows", "The Witch",
    "The Invisible Man", "The Invisible Man 2020", "Us", "Candyman 2021", "Smile", "Scream",
    "Scream 2", "Scream 3", "Scream 4", "Halloween", "Halloween II", "Halloween 2018", "Halloween Kills",
    "Halloween Ends", "Friday the 13th", "Friday the 13th Part 2", "Friday the 13th Part III",
    "Friday the 13th: The Final Chapter", "A Nightmare on Elm Street", "A Nightmare on Elm Street 2",
    "A Nightmare on Elm Street 3", "A Nightmare on Elm Street 4", "A Nightmare on Elm Street 5",
    "Freddy vs Jason", "Hellraiser", "Hellbound: Hellraiser II", "Hellraiser III", "Hellraiser: Bloodline",
    "Candyman", "The Omen", "The Omen II", "The Omen III", "The Omen 2006", "The Shining", "Doctor Sleep",
    "Pet Sematary", "Pet Sematary 2019", "Child's Play", "Child's Play 2", "Child's Play 3", "Bride of Chucky",
    "Seed of Chucky", "Curse of Chucky", "Cult of Chucky", "Chucky", "Malignant", "The Texas Chain Saw Massacre",
    "Texas Chainsaw 2022", "The Hills Have Eyes", "The Hills Have Eyes 2006", "The Hills Have Eyes 2", "Wrong Turn",
    "Wrong Turn 2003", "Wrong Turn 2", "Wrong Turn 3", "Wrong Turn 4", "Wrong Turn 5", "Wrong Turn 6", "The Blair Witch Project", "Blair Witch", "The Others", "The Sixth Sense", 
"Signs", "The Village", "Old", "Knock at the Cabin", "Split", "Glass",
"The Visit", "The Happening", "The Skeleton Key", "1408", "The Mist",
"Carrie", "Carrie (2013)", "Misery", "Cujo", "Christine", "The Dead Zone",
"The Langoliers", "Gerald’s Game", "1922", "In the Tall Grass", "The Mangler",
"The Fog", "The Fog (2005)", "The Thing", "The Thing (2011)", "They Live",
"Prince of Darkness", "In the Mouth of Madness", "Event Horizon",
"Jacob’s Ladder", "Flatliners", "Flatliners (2017)", "Silent Hill",
"Silent Hill: Revelation", "Resident Evil", "Resident Evil: Apocalypse",
"Resident Evil: Extinction", "Resident Evil: Afterlife", "Resident Evil: Retribution",
"Resident Evil: The Final Chapter", "Resident Evil: Welcome to Raccoon City",
"Underworld", "Underworld: Evolution", "Underworld: Rise of the Lycans",
"Underworld: Awakening", "Underworld: Blood Wars", "Van Helsing",
"The Wolfman", "The Mummy", "The Mummy Returns", "The Mummy: Tomb of the Dragon Emperor",
"The Mummy (2017)", "Dracula (1992)", "Dracula Untold", "Frankenstein (1931)",
"Bride of Frankenstein", "The Invisible Man Returns", "Creature from the Black Lagoon",
"Nosferatu", "Nosferatu the Vampyre", "Let the Right One In", "Let Me In",
"30 Days of Night", "Daybreakers", "Stake Land", "Near Dark", "Interview with the Vampire",
"Queen of the Damned", "Only Lovers Left Alive", "The Hunger", "Thirst",
"Crimson Peak", "Pan’s Labyrinth", "The Devil’s Backbone", "The Orphanage",
"The Wailing", "The Medium", "Shutter (2004)", "Shutter (2008)", "The Eye (2002)",
"The Eye (2008)", "Pulse", "Dark Water", "Ju-On: The Grudge", "Ju-On: The Grudge 2",
"Ju-On: White Ghost", "Ju-On: Black Ghost", "Ringu", "Ringu 2", "Ringu 0: Birthday",
"Sadako 3D", "Sadako vs Kayako", "One Missed Call", "One Missed Call (US)",
"The Call (2020)", "The Cursed", "The Closet", "Train to Busan", "Peninsula",
"The Wailing (2016)", "A Tale of Two Sisters", "I Saw the Devil", "The Host (2006)",
"Okja (dark sci-fi horror)", "Parasite (thriller-horror elements)", "The Silenced",
"The Divine Fury", "Gonjiam: Haunted Asylum", "The Medium (Thai-Korean)",
"Coming Soon (2008)", "The Maid (2020)", "The Offering", "The Pool (Thai)",
"Satan’s Slaves", "May the Devil Take You", "Impetigore", "The Queen of Black Magic",
"Munafik", "Munafik 2", "Roh", "The 3rd Eye", "The Doll", "The Doll 2", "Sebelum Iblis Menjemput",
"The Autopsy of Jane Doe", "The Possession", "The Taking of Deborah Logan",
"The Exorcism of Emily Rose", "The Last Exorcism", "The Rite", "Deliver Us from Evil",
"The Vatican Tapes", "The Pope’s Exorcist", "The Possession of Hannah Grace",
"The Exorcism of God", "The Unholy", "The Crucifixion", "The Devil Inside",
"The Nun’s Curse", "The Curse of La Llorona", "Annabelle: Creation (extended)",
"The Lazarus Effect", "The Bye Bye Man", "Mama", "Mama 2", "The Orphan",
"Orphan: First Kill", "The Boy", "Brahms: The Boy II", "Case 39", "The Good Son",
"The Prodigy", "Joshua", "We Need to Talk About Kevin", "The Omen (classic)",
"Damien: Omen II (classic)", "Omen III: The Final Conflict", "The Exorcist: Believer",
"The Pope’s Exorcist (2023)", "The Boogeyman (2023)", "Talk to Me (2023)",
"Smile 2 (2025)", "Skinamarink", "The Outwaters", "Infinity Pool", "Men (2022)",
"X (2022)", "Pearl (2022)", "Maxxxine (upcoming)", "Barbarian (2022)",
"The Black Phone", "Malignant (2021)", "Last Night in Soho", "The Menu",
"Fresh (2022)", "Infinity Pool (2023)", "Bodies Bodies Bodies", "The Lodge",
"The Night House", "Run (2020)", "Evil Dead Rise", "Evil Dead (2013)",
"The Evil Dead (1981)", "Evil Dead II", "Army of Darkness", "Ash vs Evil Dead",
"Cabin Fever", "Cabin Fever 2: Spring Fever", "Hostel", "Hostel: Part II",
"Hostel: Part III", "Saw", "Saw II", "Saw III", "Saw IV", "Saw V", "Saw VI",
"Saw VII", "Jigsaw", "Spiral: From the Book of Saw", "Texas Chainsaw Massacre (2003)",
"Leatherface (2017)", "The Collector", "The Collection", "The Strangers",
"The Strangers: Prey at Night", "Vacancy", "Vacancy 2: The First Cut",
"Wrong Turn (2021)", "House of Wax (2005)", "The House of the Devil",
"The Innkeepers", "The Invitation", "The Invitation (2022)", "The Night Eats the World",
"The Road", "Cargo", "28 Days Later", "28 Weeks Later", "28 Years Later (TBA)",
"I Am Legend", "World War Z", "Dawn of the Dead (2004)", "Dawn of the Dead (1978)",
"Day of the Dead", "Land of the Dead", "Diary of the Dead", "Survival of the Dead",
"Army of the Dead", "Army of Thieves", "Train to Busan Presents: Peninsula",
"Pontypool", "The Crazies", "The Girl with All the Gifts", "The Dead Don’t Die",
"Pride and Prejudice and Zombies", "Warm Bodies", "Fido", "Life After Beth",
"The Happening (2008)", "The Ruins", "The Descent", "The Descent 2", "As Above, So Below",
"The Cave", "The Pyramid", "The Hills Run Red", "Wrong Turn (2021)",
"House of 1000 Corpses", "The Devil’s Rejects", "3 from Hell", "Lords of Salem",
"Suspiria (1977)", "Suspiria (2018)", "Black Swan", "Mother!", "Saint Maud",
"Possessor", "Under the Skin", "The Witch (2016)", "The Lighthouse",
"The Northman (dark mythic horror)", "Antichrist", "Melancholia", "Nymphomaniac",
"The House That Jack Built", "Raw", "Titane", "The Neon Demon", "The Killing of a Sacred Deer",
"The Lobster", "Dogtooth", "Possession (1981)", "The Tenant", "Repulsion",
"The Wicker Man (1973)", "The Wicker Man (2006)", "Midsommar (2019)", "Men (2022)"
  ],
  Romance: [
    "Titanic", "La La Land", "Pride & Prejudice", "The Notebook", "A Walk to Remember",
    "Dear John", "Me Before You", "The Fault in Our Stars", "Crazy Rich Asians", "To All the Boys I've Loved Before",
    "To All the Boys: P.S. I Still Love You", "To All the Boys: Always and Forever", "The Vow", "Safe Haven",
    "Love Actually", "Notting Hill", "Four Weddings and a Funeral", "Bridget Jones's Diary", "Bridget Jones: The Edge of Reason",
    "Maid in Manhattan", "Sweet Home Alabama", "The Lucky One", "The Longest Ride", "Letters to Juliet",
    "Midnight Sun", "Remember Me", "The Age of Adaline", "The Best of Me", "Endless Love", "Becoming Jane",
    "Sense and Sensibility", "Emma", "Little Women", "Atonement", "Jane Eyre", "Wuthering Heights", "The English Patient",
    "Chocolat", "Titanic 2", "Dear Frankie", "The Painted Veil", "An Affair to Remember", "Breakfast at Tiffany's",
    "Roman Holiday", "Casablanca", "Gone with the Wind", "The Great Gatsby", "Moulin Rouge!", "Anna Karenina",
    "La La Land", "The Spectacular Now", "Blue Valentine", "Before Sunrise", "Before Sunset", "Before Midnight",
    "The Time Traveler's Wife", "Pride and Prejudice 2005", "Love & Basketball", "Step Up", "Step Up 2",
    "Step Up 3D", "Step Up Revolution", "Step Up All In", "Grease", "Grease 2", "Dirty Dancing",
    "Hitch", "Sweet Home Alabama", "Runaway Bride", "Valentine's Day", "New Year's Eve", "Hope Floats",
    "The Proposal", "The Wedding Planner", "Bride Wars", "27 Dresses", "The Princess Diaries", "Ever After",
    "Letters to Juliet", "A Cinderella Story", "Cinderella 2021", "Beauty and the Beast 2017", "Cinderella Man",
    "Leap Year", "The Lucky One", "Safe Haven", "Remember Me", "Message in a Bottle", "Love Story", "Autumn in New York",
    "The Notebook", "Dear John", "Water for Elephants", "The Choice", "Midnight Sun", "P.S. I Love You", "One Day",
    "Before We Go", "The Spectacular Now", "500 Days of Summer", "About Time", "Love, Rosie", "The Holiday", "The Lake House",
"Music and Lyrics", "Definitely, Maybe", "Crazy, Stupid, Love", "Just Like Heaven",
"While You Were Sleeping", "Sleepless in Seattle", "You've Got Mail", "Serendipity",
"Notting Hill (1999)", "Runaway Bride (1999)", "Pretty Woman", "My Best Friend’s Wedding",
"Run Lola Run", "Sliding Doors", "Closer", "Match Point", "Vicky Cristina Barcelona",
"Midnight in Paris", "To Rome with Love", "Café Society", "Manhattan", "Annie Hall",
"Love and Other Drugs", "One Fine Day", "Something’s Gotta Give", "It’s Complicated",
"The Intern (romantic subplot)", "The Adjustment Bureau", "Upside Down", "The Space Between Us",
"The Mountain Between Us", "Passengers", "Her", "Eternal Sunshine of the Spotless Mind",
"Lost in Translation", "Begin Again", "Once", "Sing Street", "August Rush",
"Inside Llewyn Davis", "Yesterday", "Across the Universe", "The Artist", "Her Smell",
"A Star Is Born (2018)", "Once (2007)", "Beyond the Lights", "Dreamgirls", "Walk the Line",
"Rocketman", "Ray", "Bohemian Rhapsody (romantic subplot)", "The Bodyguard", "Whitney Houston: I Wanna Dance with Somebody",
"Brown Sugar", "The Best Man", "The Best Man Holiday", "Think Like a Man", "Deliver Us from Eva",
"The Photograph", "If Beale Street Could Talk", "Moonlight", "Pariah", "Loving",
"Brokeback Mountain", "Carol", "Call Me by Your Name", "Portrait of a Lady on Fire",
"Blue Is the Warmest Color", "The Handmaiden", "Happy Together", "Weekend", "God’s Own Country",
"My Beautiful Laundrette", "Maurice", "Philadelphia Story", "Roman Holiday (1953)",
"Sabrina (1954)", "Sabrina (1995)", "Funny Face", "Love in the Afternoon", "Charade",
"The Umbrellas of Cherbourg", "The Young Girls of Rochefort", "Amélie", "Paris, Je T’aime",
"Chocolat (2000)", "Before the Rain", "The Dreamers", "Belle de Jour", "Blue Valentine (2010)",
"Revolutionary Road (2008)", "Marriage Story (2019)", "Closer (2004)", "The Reader (2008)",
"The English Patient (1996)", "The Remains of the Day", "A Room with a View", "Howard’s End",
"Out of Africa", "The Bridges of Madison County", "Far and Away", "Legends of the Fall",
"Meet Joe Black", "Autumn Sonata", "The Lover (1992)", "Indochine", "The Piano",
"Bright Star", "Becoming Jane (2007)", "Jane Eyre (2011)", "Wuthering Heights (2011)",
"Anna Karenina (2012)", "Doctor Zhivago", "Reds", "Casablanca (1942)", "Gone with the Wind (1939)",
"The Way We Were", "Love Story (1970)", "The Thorn Birds", "Outlander", "Cold Mountain",
"The Painted Veil (2006)", "Memoirs of a Geisha", "House of Flying Daggers", "Crouching Tiger, Hidden Dragon",
"The Flowers of War", "Raise the Red Lantern", "2046", "In the Mood for Love", "Chungking Express",
"Fallen Angels", "Days of Being Wild", "Lust, Caution", "Comrades: Almost a Love Story",
"Love in a Puff", "Love Off the Cuff", "My Blueberry Nights", "The Grandmaster",
"Your Name", "Weathering with You", "Suzume", "5 Centimeters per Second", "The Garden of Words",
"I Want to Eat Your Pancreas", "A Silent Voice", "Whisper of the Heart", "From Up on Poppy Hill",
"Howl’s Moving Castle", "Spirited Away (romantic theme)", "Castle in the Sky", "Princess Mononoke",
"The Wind Rises", "Only Yesterday", "Ocean Waves", "The Tale of the Princess Kaguya",
"Josee, the Tiger and the Fish", "Hotarubi no Mori e", "Tamako Love Story", "Liz and the Blue Bird",
"Your Lie in April", "Violet Evergarden: The Movie", "Ride Your Wave", "The Night Is Short, Walk On Girl",
"Love Letter (1995)", "April Story", "Be with You (2004)", "Crying Out Love in the Center of the World",
"Norwegian Wood", "Our Little Sister", "After the Storm", "Shoplifters (romantic undertone)",
"Drive My Car (2021)", "Decision to Leave (2022)", "The Beauty Inside", "Always (2011)",
"A Moment to Remember", "The Classic", "Il Mare", "Windstruck", "My Girl and I",
"My Sassy Girl", "200 Pounds Beauty", "The Art of Seduction", "Love Forecast",
"Architecture 101", "Tune in for Love", "On Your Wedding Day", "20th Century Girl",
"More than Blue", "Werewolf Boy", "The Handmaiden (romantic thriller)", "The King and the Clown",
"Secretly Greatly", "The Man Standing Next", "Cyrano Agency", "Love 911", "Mood of the Day",
"Time", "3-Iron", "Spring, Summer, Fall, Winter... and Spring", "Always (Korean remake)",
"Notebook (Bangladeshi remake)", "Barfi!", "Rockstar", "Tamasha", "Yeh Jawaani Hai Deewani",
"Kal Ho Naa Ho", "Kabhi Alvida Naa Kehna", "Veer-Zaara", "Rab Ne Bana Di Jodi",
"Dilwale Dulhania Le Jayenge", "Dil To Pagal Hai", "Kuch Kuch Hota Hai", "Mohabbatein",
"Hum Dil De Chuke Sanam", "Devdas (2002)", "Saawariya", "Jab We Met", "Love Aaj Kal",
"Rockstar (2011)", "Ae Dil Hai Mushkil", "Tamasha (2015)", "Zindagi Na Milegi Dobara",
"Dil Chahta Hai", "Wake Up Sid", "Kalank", "Kabir Singh", "Shershaah",
"Laila Majnu (2018)", "Qala", "Bulbbul (romantic gothic)", "Gangubai Kathiawadi (tragic love)",
"Jodha Akbar", "Padmaavat", "Ram-Leela", "Bajirao Mastani", "Lootera",
"Raanjhanaa", "Tanu Weds Manu", "Tanu Weds Manu Returns", "Bareilly Ki Barfi",
"Badhaai Do", "Chandigarh Kare Aashiqui", "Dear Zindagi", "Highway (2014)",
"Jab Tak Hai Jaan", "Ek Villain", "Half Girlfriend", "Aashiqui", "Aashiqui 2",
"Fanaa", "Hum Tum", "Salaam Namaste", "Anjaana Anjaani", "Bachna Ae Haseeno",
"Bunty Aur Babli", "Befikre", "Tamasha (romantic arc)", "Barfi! (2012)", "Rustom"
  ],
  Thriller: [
    "Se7en", "Gone Girl", "Shutter Island", "The Silence of the Lambs", "Zodiac", "Prisoners",
    "The Girl with the Dragon Tattoo", "The Girl Who Played with Fire", "The Girl Who Kicked the Hornets' Nest",
    "Mystic River", "No Country for Old Men", "Nightcrawler", "Split", "Glass", "Unbreakable",
    "Memento", "The Machinist", "Fight Club", "Inception", "Tenet", "Insomnia", "Cape Fear",
    "Basic Instinct", "Body Heat", "Double Indemnity", "Rear Window", "Vertigo", "North by Northwest",
    "Psycho", "Dial M for Murder", "Strangers on a Train", "The Others", "The Sixth Sense", "The Village",
    "Signs", "The Happening", "Disturbia", "Red Eye", "The Bone Collector", "The Net", "Enemy of the State",
    "The Fugitive", "Air Force One", "Man on Fire", "The Constant Gardener", "Inside Man", "Runaway Jury",
    "Heat", "Collateral", "The Departed", "Gone Baby Gone", "Primal Fear", "The Insider", "Michael Clayton",
    "Body of Lies", "Eastern Promises", "Sicario", "Sicario: Day of the Soldado", "Hell or High Water", "Nocturnal Animals",
    "Wind River", "Blue Ruin", "Green Room", "10 Cloverfield Lane", "Bird Box", "The Call", "The Commuter",
    "The Equalizer", "The Equalizer 2", "Safe House", "Shooter", "Non-Stop", "Run All Night", "Unknown",
    "The Transporter", "Transporter 2", "Transporter 3", "The Accountant", "Man from U.N.C.L.E.", "Mission: Impossible",
    "Mission: Impossible 2", "Mission: Impossible III", "Mission: Impossible – Ghost Protocol", "Mission: Impossible – Rogue Nation",
    "Mission: Impossible – Fallout", "The Bourne Identity", "The Bourne Supremacy", "The Bourne Ultimatum", "Jason Bourne",
    "Tinker Tailor Soldier Spy", "Body Heat", "Basic Instinct", "Death Wish", "Death Wish 2", "Death Wish 3", "Death Wish 4", "The Prestige", "The Illusionist", "Enemy", "The Invitation", "Coherence", "Triangle",
"Exam", "The Game", "The Usual Suspects", "The Departed (extended)", "Donnie Brasco",
"Reservoir Dogs", "Pulp Fiction", "Jackie Brown", "True Romance", "Killing Them Softly",
"American Psycho", "The American", "Drive", "Only God Forgives", "The Neon Demon",
"Mulholland Drive", "Lost Highway", "Blue Velvet", "Twin Peaks: Fire Walk with Me",
"Zodiac (2007)", "Gone Girl (2014)", "Girl on the Train", "Tell No One", "Secret Window",
"The Number 23", "Identity", "Frailty", "Arlington Road", "The Gift (2015)",
"The Vanishing (1988)", "The Vanishing (1993)", "The Invisible Guest", "The Body (2012)",
"The Platform", "Timecrimes", "The Others (2001)", "What Lies Beneath", "Single White Female",
"Fatal Attraction", "Disclosure", "Sleeping with the Enemy", "Enough", "The Hand That Rocks the Cradle",
"Fear", "Panic Room", "The Game (1997)", "Phone Booth", "Changing Lanes", "The Lincoln Lawyer",
"Fracture", "Law Abiding Citizen", "A Perfect Murder", "Deception", "Chloe",
"Match Point (2005)", "Cassandra’s Dream", "Irrational Man", "Crimes and Misdemeanors",
"Manhunter", "Red Dragon", "Hannibal", "Hannibal Rising", "Copycat", "The Bone Collector (expanded)",
"Kiss the Girls", "Along Came a Spider", "Alex Cross", "The Taking of Pelham 123 (2009)",
"Inside Man (2006)", "The Negotiator", "16 Blocks", "Out of Time", "Deja Vu", "Déjà Vu (2006)",
"Unstoppable", "Flightplan", "Non-Stop (2014)", "The Grey", "The Next Three Days", "Unknown (2011)",
"Run All Night (2015)", "A Walk Among the Tombstones", "Murder on the Orient Express (2017)",
"Death on the Nile (2022)", "Knives Out", "Glass Onion: A Knives Out Mystery",
"Clue (1985)", "Gosford Park", "Murder by Death", "Identity (2003)",
"Perfect Strangers (Italian)", "The Guilty (Danish)", "The Guilty (2021)",
"Searching", "Missing (2023)", "Run (2020)", "The Invitation (2022)", "Ready or Not",
"The Hunt (2020)", "Get Out (2017)", "Us (2019)", "No Exit (2022)", "Don’t Worry Darling",
"The Menu", "Infinity Pool", "Fresh (2022)", "Vivarium", "The Circle (2017)",
"Source Code", "Looper", "Limitless", "Lucy", "Transcendence", "Upgrade",
"Ex Machina", "Annihilation", "Sunshine", "Moon", "The Signal", "Under the Skin",
"The Machinist (2004)", "The Prestige (2006)", "The Butterfly Effect", "Stay",
"Shutter Island (2010)", "Side Effects", "Contagion", "The Informant!", "Michael Clayton (2007)",
"Syriana (2005)", "Body of Lies (2008)", "Argo", "Zero Dark Thirty", "Munich",
"Hotel Mumbai", "Beirut", "Green Zone", "The Kingdom", "The Manchurian Candidate (2004)",
"The Parallax View", "Three Days of the Condor", "All the President’s Men", "The Conversation",
"Enemy of the State (1998)", "Sneakers", "Spy Game", "Tinker Tailor Soldier Spy (2011)",
"The Constant Gardener (2005)", "The Interpreter", "The Ghost Writer", "Eye in the Sky",
"Good Kill", "Drone", "Eye for an Eye", "The Siege", "Patriot Games (1992)",
"Clear and Present Danger (1994)", "Jack Ryan: Shadow Recruit", "Without Remorse",
"The Sum of All Fears", "13 Hours: The Secret Soldiers of Benghazi", "Captain Phillips",
"United 93", "Flight 93", "Sully", "The Terminal (thriller elements)",
"The 9th Gate", "Rosemary’s Baby", "The Tenant", "Repulsion", "Black Swan (2010)",
"Mother! (2017)", "Under the Silver Lake", "It Comes at Night", "The Killing of a Sacred Deer",
"The Lobster", "Dogtooth", "The House That Jack Built", "Nymphomaniac", "Antichrist",
"Melancholia", "The Vanishing Point", "Drive (2011)", "Crash (1996)", "eXistenZ",
"Hard Candy", "Gone Baby Gone (2007)", "Mystic River (2003)", "Gran Torino (thriller tone)",
"Changeling (2008)", "Play Misty for Me", "High Plains Drifter", "Tightrope", "Absolute Power",
"In the Line of Fire", "The Mule (thriller)", "Richard Jewell", "American Sniper (thriller aspect)",
"The Mule (2018)", "Prisoners (2013)", "Enemy (2013)", "Sicario (2015)", "Sicario: Day of the Soldado (2018)",
"Wind River (2017)", "Hell or High Water (2016)", "Nocturnal Animals (2016)",
"Nightcrawler (2014)", "Drive (2011)", "A History of Violence", "Eastern Promises (2007)",
"Crash (2004)", "The Fly (1986)", "Dead Ringers (1988)", "Maps to the Stars", "Cosmopolis",
"Videodrome", "Scanners", "The Brood", "The Dead Zone (1983)", "Cronenberg’s Crimes of the Future",
"Tenet (2020)", "Oppenheimer (2023)", "Inception (2010)", "Insomnia (2002)", "Following (1998)",
"Memento (2000)", "The Prestige (2006)", "Interstellar (thriller angle)", "The Dark Knight (thriller)",
"The Batman (2022)", "The Joker (2019)", "The Pale Blue Eye", "The Snowman", "The Girl in the Spider’s Web",
"The Secret in Their Eyes", "El Secreto de Sus Ojos (2009)", "The Invisible Guest (2016)",
"The Body (El Cuerpo)", "The Skin I Live In", "Open Your Eyes", "Vanilla Sky",
"The Others (Spanish influence)", "Timecrimes (Los Cronocrímenes)", "The Platform (2019)",
"Contratiempo", "Marrowbone", "Julia’s Eyes", "Sleep Tight", "The Orphanage (2007)",
"The Hidden Face", "The Invisible Man (2020)", "Oxygen (2021)", "Buried (2010)",
"Locke (2013)", "Phone Booth (2002)", "127 Hours (2010)", "Gravity (2013)",
"All Is Lost", "The Martian (thriller mix)", "Ad Astra", "Moon (2009)", "Pandorum",
"Event Horizon (1997)", "Sunshine (2007)", "Life (2017)", "Cloverfield", "10 Cloverfield Lane (2016)",
"The Cloverfield Paradox", "The Invitation (thriller)", "Run (thriller)", "Missing (thriller 2023)"
  ],
  SciFi: [
    "Interstellar", "Inception", "The Matrix", "The Matrix Reloaded", "The Matrix Revolutions", "The Terminator",
    "Terminator 2: Judgment Day", "Terminator 3", "Terminator Salvation", "Terminator Genisys", "Terminator: Dark Fate",
    "Avatar", "Avatar: The Way of Water", "Star Wars: A New Hope", "Star Wars: The Empire Strikes Back",
    "Star Wars: Return of the Jedi", "Star Wars: The Force Awakens", "Star Wars: The Last Jedi",
    "Star Wars: The Rise of Skywalker", "Rogue One: A Star Wars Story", "Solo: A Star Wars Story",
    "Guardians of the Galaxy", "Guardians of the Galaxy Vol. 2", "Avengers: Infinity War", "Avengers: Endgame",
    "Doctor Strange", "Doctor Strange in the Multiverse of Madness", "Thor", "Thor: Ragnarok", "Thor: Love and Thunder",
    "Black Panther", "Black Panther: Wakanda Forever", "Ant-Man", "Ant-Man and the Wasp", "Spider-Man: No Way Home",
    "Spider-Man: Far From Home", "Spider-Man: Homecoming", "Spider-Man: Into the Spider-Verse",
    "Batman v Superman: Dawn of Justice", "Justice League", "Zack Snyder's Justice League", "Aquaman",
    "Shazam!", "Wonder Woman", "Wonder Woman 1984", "Suicide Squad", "The Suicide Squad", "The Flash",
    "Guardians of the Galaxy", "Guardians of the Galaxy Vol. 2", "Inception", "Dune", "Dune 2021", "Blade Runner",
    "Blade Runner 2049", "Arrival", "Minority Report", "Edge of Tomorrow", "Looper", "Oblivion", "Jupiter Ascending",
    "The Fifth Element", "Total Recall", "Star Trek", "Star Trek Into Darkness", "Star Trek Beyond", "Star Trek 2009",
    "Star Trek 2013", "The Martian", "Prometheus", "Alien", "Aliens", "Alien 3", "Alien: Resurrection", "Alien: Covenant",
    "Predator", "Predator 2", "Predators", "The Predator", "Interstellar", "Gravity", "Moon", "Sunshine", "Elysium",
    "Passengers", "Ender's Game", "The Hunger Games", "Catching Fire", "Mockingjay Part 1", "Mockingjay Part 2",
    "Ready Player One", "The Tomorrow War", "Oblivion", "Edge of Tomorrow", "2001: A Space Odyssey", "2010: The Year We Make Contact", "Close Encounters of the Third Kind",
"E.T. the Extra-Terrestrial", "A.I. Artificial Intelligence", "War of the Worlds (2005)",
"The Day the Earth Stood Still (1951)", "The Day the Earth Stood Still (2008)",
"The Abyss", "Contact", "Event Horizon", "Sphere", "Solaris (1972)", "Solaris (2002)",
"Moon (2009)", "Europa Report", "Ad Astra", "Life (2017)", "Sunshine (2007)",
"Pitch Black", "The Chronicles of Riddick", "Riddick", "Pandorum", "Dark City",
"Equilibrium", "Gattaca", "Children of Men", "A Scanner Darkly", "The Adjustment Bureau",
"Limitless", "Transcendence", "Lucy", "Her", "Ex Machina", "Annihilation",
"Under the Skin", "Upgrade", "The Machine", "Automata", "I, Robot", "I Am Legend",
"The Island", "Oblivion (2013)", "Tron", "Tron: Legacy", "Total Recall (1990)",
"Demolition Man", "Judge Dredd", "Dredd", "Robocop", "Robocop 2", "Robocop (2014)",
"The Running Man", "Virtuosity", "Johnny Mnemonic", "Freejack", "Strange Days",
"Ghost in the Shell (1995)", "Ghost in the Shell (2017)", "Akira", "Paprika",
"Perfect Blue", "Steins;Gate: The Movie – Load Region of Déjà Vu", "Your Name (sci-fi themes)",
"Weathering with You (sci-fi elements)", "5 Centimeters per Second", "Metropolis (1927)",
"Metropolis (2001 anime)", "The Iron Giant", "Big Hero 6", "Treasure Planet",
"Wall-E", "Inside Out", "Soul", "Lightyear", "The Incredibles", "The Incredibles 2",
"Tomorrowland", "John Carter", "The Black Hole (1979)", "Tron: Legacy (2010)",
"Treasure Planet (2002)", "Atlantis: The Lost Empire", "Atlantis: Milo’s Return",
"The Time Machine (1960)", "The Time Machine (2002)", "The Butterfly Effect",
"Source Code", "The One", "Jet Li’s The One", "Push", "Jumper", "Chronicle",
"Power Rangers (2017)", "Fantastic Four (2005)", "Fantastic Four: Rise of the Silver Surfer",
"Fantastic Four (2015)", "The Invisible Man (2020)", "The Mummy Returns (sci-fi lean)",
"The League of Extraordinary Gentlemen", "Constantine", "Watchmen", "V for Vendetta",
"Sin City", "Sin City: A Dame to Kill For", "Snowpiercer", "The Host (2006 Korean)",
"Okja", "Parasite (satirical sci-fi undertone)", "Train to Busan Presents: Peninsula",
"The Wailing (cosmic horror)", "Space Sweepers", "Alienoid", "The Wandering Earth",
"The Wandering Earth 2", "The Three-Body Problem (China)", "The Great Wall (fantasy-sci-fi)",
"Kung Fury", "Turbo Kid", "Iron Sky", "Iron Sky: The Coming Race", "Mutant Chronicles",
"Doomsday (2008)", "The Book of Eli", "Z for Zachariah", "The Postman",
"Waterworld", "Mad Max", "Mad Max 2: The Road Warrior", "Mad Max Beyond Thunderdome",
"Mad Max: Fury Road (sci-fi classification)", "District 9", "Chappie", "Elysium (2013)",
"Monsters (2010)", "Monsters: Dark Continent", "Cloverfield", "10 Cloverfield Lane",
"The Cloverfield Paradox", "Super 8", "Edge of Tomorrow (2014)", "Live Die Repeat",
"The Tomorrow War (2021)", "Battle: Los Angeles", "Independence Day", "Independence Day: Resurgence",
"Skyline", "Beyond Skyline", "Skylines", "Cloverfield (2008)", "Pacific Rim",
"Pacific Rim: Uprising", "Transformers", "Transformers: Revenge of the Fallen",
"Transformers: Dark of the Moon", "Transformers: Age of Extinction",
"Transformers: The Last Knight", "Bumblebee", "Transformers: Rise of the Beasts",
"Real Steel", "I, Robot (2004)", "Chappie (2015)", "Short Circuit", "Short Circuit 2",
"Bicentennial Man", "The Stepford Wives (1975)", "The Stepford Wives (2004)",
"Westworld (1973)", "Futureworld (1976)", "AI: Artificial Intelligence (2001)",
"Blade Runner (1982)", "Blade Runner 2049 (2017)", "Alien (1979)", "Aliens (1986)",
"Alien 3 (1992)", "Alien: Resurrection (1997)", "Alien: Covenant (2017)", "Predator (1987)",
"Predator 2 (1990)", "Predators (2010)", "The Predator (2018)", "Prey (2022)",
"Prometheus (2012)", "Sunshine (2007)", "Gravity (2013)", "Interstellar (2014)",
"The Martian (2015)", "Passengers (2016)", "Ad Astra (2019)", "Moon (2009)",
"High Life (2018)", "Solaris (1972)", "Solaris (2002)", "Silent Running (1972)",
"Dark Star (1974)", "The Man Who Fell to Earth (1976)", "The Andromeda Strain (1971)",
"The Omega Man (1971)", "Soylent Green (1973)", "THX 1138", "Logan’s Run (1976)",
"Altered States (1980)", "Scanners (1981)", "Videodrome (1983)", "The Fly (1986)",
"Naked Lunch (1991)", "eXistenZ (1999)", "Crimes of the Future (2022)",
"Possessor (2020)", "Upgrade (2018)", "Lucy (2014)", "Limitless (2011)",
"Transcendence (2014)", "The Lawnmower Man", "Johnny Mnemonic (1995)",
"The Net (1995)", "Hackers (1995)", "Swordfish", "Sneakers (1992)", "Enemy of the State (1998)",
"Eagle Eye", "Deja Vu (2006)", "Minority Report (2002)", "Paycheck (2003)",
"Oblivion (2013)", "I, Robot (2004)", "Surrogates (2009)", "Replicas (2018)",
"The 6th Day (2000)", "The Thirteenth Floor (1999)", "Dark City (1998)",
"Cube (1997)", "Cube 2: Hypercube (2002)", "Cube Zero (2004)", "Splice (2009)",
"Species (1995)", "Species II (1998)", "The Astronaut’s Wife (1999)", "Contact (1997)",
"Arrival (2016)", "Annihilation (2018)", "Interstellar (extended)", "Oppenheimer (2023 sci-fi drama)"
  ]
};

document.addEventListener("DOMContentLoaded", () => {
  const loader = document.getElementById("loader");
  const movieCard = document.getElementById("movie-card");
  const refreshBtn = document.getElementById("refresh-btn");
  const genreButtonsContainer = document.querySelector(".genre-buttons");
  const genreMovieContainer = document.getElementById("genre-movie-container");

  if (!loader || !movieCard || !genreButtonsContainer || !genreMovieContainer) return;

  function showLoading() {
    loader.classList.add("active");
    loader.querySelector(".cube-stack")?.classList.remove("stopped");
  }

  function hideLoading() {
    loader.querySelector(".cube-stack")?.classList.add("stopped");
    loader.classList.remove("active");
  }

  async function fetchMovie(title) {
    try {
      const res = await fetch(`https://www.omdbapi.com/?t=${encodeURIComponent(title)}&apikey=${API_KEY}`);
      const data = await res.json();
      return data.Response === "True" ? data : null;
    } catch {
      return null;
    }
  }

  async function showRandomMovie() {
    showLoading();
    const timeout = setTimeout(() => hideLoading(), 10000);

    try {
      const genres = Object.keys(genreMovies);
      const randomGenre = genres[Math.floor(Math.random() * genres.length)];
      const titles = genreMovies[randomGenre];
      const randomTitle = titles[Math.floor(Math.random() * titles.length)];

      const movie = await fetchMovie(randomTitle);

      movieCard.innerHTML = movie ? `
        <img class="movie-poster" src="${movie.Poster}" alt="${movie.Title}">
        <div class="movie-info">
          <h2>${movie.Title}</h2>
          <p>${movie.Plot}</p>
          <div class="movie-meta">
            <span>Actors: ${movie.Actors}</span>
            <span>Genre: ${movie.Genre}</span>
          </div>
        </div>
      ` : `<p>Movie not found</p>`;
    } finally {
      clearTimeout(timeout);
      hideLoading();
    }
  }

  async function showGenreMovies(genre) {
    genreMovieContainer.innerHTML = "";
    showLoading();
    const titles = genreMovies[genre];
    const selectedTitles = [];

    while (selectedTitles.length < 6) {
      const randomTitle = titles[Math.floor(Math.random() * titles.length)];
      if (!selectedTitles.includes(randomTitle)) selectedTitles.push(randomTitle);
    }

    const movies = await Promise.all(selectedTitles.map(title => fetchMovie(title)));

    genreMovieContainer.innerHTML = movies
      .filter(m => m)
      .map(m => `
        <div class="movie-card">
          <img src="${m.Poster}" alt="${m.Title}">
          <h3>${m.Title}</h3>
        </div>
      `).join("");

    hideLoading();
  }

  Object.keys(genreMovies).forEach(genre => {
    const btn = document.createElement("button");
    btn.textContent = genre;
    btn.addEventListener("click", () => showGenreMovies(genre));
    genreButtonsContainer.appendChild(btn);
  });

  refreshBtn.addEventListener("click", showRandomMovie);

  showRandomMovie();

});

